name: jamestmather
favicon: null
layout_spectrum: 0.6918605917599052
typography_spectrum: 0.3646152704022825
title: jamestmather
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f5ffff'
    - '#355c6d'
    - '#7b99a3'
    - '#d4d9d2'
  brandStrength: 0.6888668900355697
  lightness: 0.625
  saturation: 0.7989849490113556
  rhythmicContrast: 0.75
purpose: []
